[theme]
font="Nunito:https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000, sans-serif"
codeFont="'Space Mono':https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap, monospace"
baseRadius="none"
buttonRadius="none"
showSidebarBorder=true
primaryColor="#f54a00"

[logger]
messageFormat="%(asctime)s %(levelname)s $(component) %(message)s"
